FROM ubuntu:latest
RUN apt-get update && \
    apt-get install -y clang  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY Source.cpp .
RUN clang++ -o program Source.cpp
CMD ["./program"]